M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-04T01:18:58+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-04T01:18:58+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X127.685Y-93.46
X132.535Y-93.46
T2
X127.385Y-90.43
X132.835Y-90.43
M30
